// MissionSwarm — core data model (ms-001)
//
// These are the shapes everything else builds on. Criteria:
//
//  1. JSON-serializable end-to-end so `simulations/<id>/state.json`
//     round-trips cleanly. No Date objects, no Maps, no class
//     instances — strings and plain records only.
//  2. Readable-by-grep. File-on-disk is primary persistence; a
//     human running `jq` or opening the file in VS Code should
//     make sense of the state without a guidebook.
//  3. Stance + interest modeled as open Record<topic, number>
//     rather than fixed fields. Topics are emergent — the persona
//     generator (ms-003) may surface topics the audience profile
//     didn't anticipate. Locking a fixed schema would force us to
//     enumerate every conceivable dimension up front.
//  4. Deltas modeled the same way as absolute values (Record<topic,
//     number>) so stance_delta + stance_before = stance_after is
//     trivial arithmetic downstream. The loop applies deltas in
//     ms-004.
//
// If a future task needs new fields, extend in place — these
// interfaces are v0 design, not forever-sealed. Capture the
// rationale in a comment when doing so.

// ─────────────────────────────────────────────────────────────
// §1 Topics + numeric scales
// ─────────────────────────────────────────────────────────────

/**
 * A topic label used in stance / interest maps. Kept as a plain
 * string rather than a branded type because topics are emergent
 * from the persona generator, not enumerated in advance. The
 * LLM decides what "topics" the input document touches and
 * names them in its output.
 *
 * Conventions (advisory, not enforced):
 *  - Snake_case lowercase, e.g. "escalation_risk", "domestic_unity".
 *  - Avoid punctuation; tools will grep these.
 */
export type Topic = string;

/**
 * Stance value. Range −1.0 to +1.0.
 *  +1.0 = maximum agreement / support
 *   0.0 = neutral / ambivalent / no stated position
 *  −1.0 = maximum disagreement / opposition
 *
 * Values outside the range are allowed but discouraged — the
 * persona generator and round loop clamp when they write these,
 * but consumers shouldn't rely on that happening.
 */
export type StanceValue = number;

/**
 * Interest value. Range 0.0 to 1.0.
 *  1.0 = this topic is central to the persona's identity
 *  0.5 = the persona cares and will comment
 *  0.0 = the persona will likely ignore this topic
 *
 * Combined with stance, the pair (stance, interest) answers two
 * questions: *how* does this persona feel about X, and *how much*
 * do they care about X.
 */
export type InterestValue = number;

// ─────────────────────────────────────────────────────────────
// §2 Persona
// ─────────────────────────────────────────────────────────────

/**
 * A single simulated participant in a swarm. Generated once at
 * simulation start (ms-003) from the audience profile + input
 * document, then mutated over rounds via reaction-emitted deltas.
 *
 * `id` is deterministic: `${simulation_id}-${index}` where index
 * is the position in the generated persona array. This makes
 * re-runs with the same input reproducible if/when we add
 * seeding.
 */
export interface Persona {
  id: string;
  name: string;
  /**
   * A few sentences of backstory + voice cues. This is the full
   * prompt-context for the persona's reactions — no separate
   * persona-prompt layer. The bio carries everything the LLM
   * needs to maintain voice consistency across rounds.
   */
  bio: string;
  /**
   * Stance-per-topic. Initial values come from the generator;
   * subsequent rounds mutate via reaction.stance_delta. Topics
   * not present in the record are treated as stance 0 (neutral).
   */
  stance: Record<Topic, StanceValue>;
  /**
   * Interest-per-topic. Mutated over rounds like stance. Absent
   * topics treated as interest 0.
   */
  interest: Record<Topic, InterestValue>;
  /**
   * Free-text markers captured by the generator — "speaks in
   * clipped military tone", "sprinkles Yiddish loanwords",
   * "uses legal register". These get concatenated into reaction
   * prompts so voice stays consistent. Kept as an array to make
   * per-marker editing ergonomic.
   */
  style_markers: string[];
}

// ─────────────────────────────────────────────────────────────
// §3 Reaction + Round
// ─────────────────────────────────────────────────────────────

/**
 * One persona's emission within one round. `text` is the public
 * output (what the audience of the simulation sees); the deltas
 * are private state mutations applied to the persona after the
 * reaction is recorded.
 *
 * Generated by the LLM via a structured prompt per ms-004. The
 * round loop parses the response and fills this shape.
 */
/**
 * Stream / CLI-facing shape for one persona reaction (newline JSON or SSE).
 * Maps from {@link Reaction} with human-readable `persona_name` and `reaction` text.
 */
export interface ReactionEvent {
  round: number;
  persona_name: string;
  reaction: string;
  stance_delta: Record<Topic, StanceValue>;
  /** Present when the model emitted interest deltas for this reaction. */
  interest_delta?: Record<Topic, InterestValue>;
}

export interface Reaction {
  round_n: number;
  persona_id: string;
  text: string;
  /**
   * Change to this persona's stance on each topic, applied after
   * the reaction is emitted. Sparse — only topics the persona
   * actually updated in this round. Topics absent from the
   * record mean "no change in this round" (NOT "set to zero").
   */
  stance_delta: Record<Topic, StanceValue>;
  /**
   * Same shape as stance_delta, for interest changes. Same
   * sparse semantics.
   */
  interest_delta: Record<Topic, InterestValue>;
}

/**
 * All reactions emitted in a single round. Kept as a first-class
 * type (rather than just an array of Reaction) so round-level
 * metadata (timing, the input-doc revision the round saw, etc.)
 * can attach later without reshaping.
 */
export interface Round {
  number: number;
  reactions: Reaction[];
  /**
   * ISO 8601 timestamp when this round's LLM calls started.
   * Useful for debugging latency + figuring out which rounds
   * were slow without parsing the session log.
   */
  started_at: string;
  /**
   * ISO 8601 timestamp when all this round's reactions had been
   * recorded. `completed_at - started_at` is the wall-clock cost
   * of the round.
   */
  completed_at: string;
}

// ─────────────────────────────────────────────────────────────
// §4 Audience profile
// ─────────────────────────────────────────────────────────────

/**
 * A reusable audience template. Each simulation references one
 * profile; the persona generator consumes it to produce the
 * initial persona set.
 *
 * Profiles live on disk at `audiences/<id>.json`. Ray's kriegspiel
 * profile is the v1 flagship (ms-005). Profiles are read-only at
 * simulation time — if the guidance needs updating, write a new
 * profile file with a new id.
 */
export interface AudienceProfile {
  id: string;
  name: string;
  /**
   * Short human-readable summary, 1–2 sentences. Shown in CLI
   * list output and may be surfaced in future UIs. Not fed to
   * the LLM.
   */
  description: string;
  /**
   * The free-text prompt guidance the persona generator (ms-003)
   * feeds the LLM alongside the input document. Tells the LLM
   * what kind of personas to generate — the faction mix, the
   * voice range, the stance variety to enforce. Load-bearing;
   * this is where audience expertise gets encoded.
   */
  persona_template_guidance: string;
}

// ─────────────────────────────────────────────────────────────
// §5 Simulation config + state
// ─────────────────────────────────────────────────────────────

/**
 * User-specified inputs to a simulation run. Written to
 * `simulations/<id>/config.json` at start; never mutated after
 * that. If a user wants a different config they start a new run.
 */
export interface SimulationConfig {
  /**
   * Path to the input document (press release, brief, event
   * summary) OR its inline text. Path-vs-inline disambiguated
   * by starts-with-a-filesystem-prefix check in the CLI loader
   * (ms-006). State.json always stores the *resolved text*, not
   * the path, so replaying a simulation against a renamed file
   * still works.
   */
  input_doc: string;
  audience_profile_id: string;
  n_agents: number;
  n_rounds: number;
  /**
   * Which LLM model to use. Free-form string passed through to
   * the provider unchanged. If unset, the provider uses its
   * configured default (see ms-002).
   */
  llm_model?: string;
}

/**
 * Run status. Rounds can still be present when status is
 * "failed" — failure mid-simulation preserves partial progress
 * so reruns can resume or diff.
 */
export type SimulationStatus = "pending" | "running" | "complete" | "failed";

/**
 * The full simulation state, JSON-serializable. Written to
 * `simulations/<id>/state.json` after each round completes.
 *
 * Round-trip invariant: `JSON.parse(JSON.stringify(state))` is
 * deep-equal to the original. No Dates, no Maps, no Sets.
 */
export interface SimulationState {
  /**
   * Stable identifier — used in persona ids, state filename,
   * log prefixes. UUID v4 or short timestamp-prefixed random
   * string both fine; the CLI generates this at run start.
   */
  id: string;
  config: SimulationConfig;
  /**
   * Resolved audience profile — captured at run start, not
   * re-resolved from disk each round. Makes replays safe if
   * the profile file changes between runs.
   */
  audience: AudienceProfile;
  /**
   * Resolved input document text — see SimulationConfig.input_doc
   * comment. Captured here so state.json is self-sufficient for
   * replay / analysis.
   */
  resolved_input_doc: string;
  /**
   * Generated personas, in the order the generator emitted them.
   * Mutated over rounds (stance + interest drift). Length always
   * equals config.n_agents.
   */
  personas: Persona[];
  /**
   * Completed rounds, in order. Length grows from 0 to
   * config.n_rounds as the simulation progresses. An active
   * in-progress round does NOT appear here — only appended once
   * all its reactions are recorded.
   */
  rounds: Round[];
  status: SimulationStatus;
  /** ISO 8601 timestamp — when the run started. */
  started_at: string;
  /**
   * ISO 8601 timestamp — when the run reached a terminal state
   * ("complete" or "failed"). Absent while status is "pending"
   * or "running".
   */
  completed_at?: string;
  /**
   * If status is "failed", a human-readable reason. Absent on
   * non-failure states.
   */
  failure_reason?: string;
}

// ─────────────────────────────────────────────────────────────
// §6 Helper: apply a reaction's deltas to a persona
// ─────────────────────────────────────────────────────────────

/**
 * Returns a new Persona with this reaction's deltas applied.
 * Deliberately in types.ts rather than a separate module because
 * the delta-application rule is part of the type contract: it
 * defines what a Reaction *means* relative to the Persona state.
 *
 * Mutation rules:
 *  - Topic present in persona but not in delta: unchanged.
 *  - Topic present in delta but not in persona: added at
 *    delta value (so a round can surface a new topic the
 *    persona previously had no position on).
 *  - Topic in both: sum, clamped to the valid range
 *    (stance [−1, +1], interest [0, 1]).
 */
export function applyReactionToPersona(
  persona: Persona,
  reaction: Reaction,
): Persona {
  if (reaction.persona_id !== persona.id) {
    throw new Error(
      `Reaction.persona_id "${reaction.persona_id}" does not match Persona.id "${persona.id}"`,
    );
  }
  const nextStance: Record<Topic, StanceValue> = { ...persona.stance };
  for (const [topic, delta] of Object.entries(reaction.stance_delta)) {
    const prev = nextStance[topic] ?? 0;
    nextStance[topic] = clamp(prev + delta, -1, 1);
  }
  const nextInterest: Record<Topic, InterestValue> = { ...persona.interest };
  for (const [topic, delta] of Object.entries(reaction.interest_delta)) {
    const prev = nextInterest[topic] ?? 0;
    nextInterest[topic] = clamp(prev + delta, 0, 1);
  }
  return { ...persona, stance: nextStance, interest: nextInterest };
}

function clamp(x: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, x));
}
